version: '3.7'

services:

  web:
    build: .
    command: run-services nginx,php-fpm
    environment:
      APP_NAME: project-name
      APP_ENV: local
      XDEBUG_CONFIG: remote_enable=1
      PHP_IDE_CONFIG: serverName=localhost
      PHP_OPCACHE_BLACKLIST_FILENAME: /app/.elephantbox/opcache-blacklist.local
    ports:
      - 8000:80
    volumes:
      - .:/app
      - ~/.composer/auth.json:/root/.config/composer/auth.json
    links:
      - mysql
      - redis

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project-name
      MYSQL_USER: project-name
      MYSQL_PASSWORD: project-name

  redis:
    image: redis:latest

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
